const _BASE_URL_ADM_DOMAIN = process.env["BASE_URL_ADM_DOMAIN"];
const _BASE_URL_ESTUDANTE_DOMAIN = process.env["BASE_URL_ESTUDANTE_DOMAIN"];

export const environment = {
  production: false,
  BASE_URL_ADM_DOMAIN: _BASE_URL_ADM_DOMAIN,
  BASE_URL_ESTUDANTE_DOMAIN:_BASE_URL_ESTUDANTE_DOMAIN
};